"""
1. Fill the logo slots (index.html partials and page-specific ones) from the client's files in assets/brand/
   (Update 01: the logo is always the client's file, never retyped).
2. Copy the shared PARTIAL blocks (header, footer, bag, search) from index.html
   into every other page, so the chrome stays byte-identical across the site.
4. product.html: a tiny head script that preloads the product's first image
   (from js/data/products.js), so the LCP image is fetched before the page JS runs.
3. Write each page's <link rel="modulepreload"> list from its real import graph
   (between the MODULEPRELOAD markers in <head>), so the browser fetches every
   module at once instead of one import level per round trip.

    python tools/sync-partials.py          # fill logos + sync
    python tools/sync-partials.py --check  # exit 1 if any page has drifted

Logo slots look like:
    <!-- LOGO:inline jiai-wordmark.svg -->...<!-- /LOGO -->        inline SVG (header: the dot animates)
    <!-- LOGO:img jiai-logo.svg alt="..." width=150 -->...<!-- /LOGO -->   <img>
While a file is missing, the slot keeps its interim content and the script says so.

Dev tool only: not needed on the server.
"""
import posixpath
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / "assets" / "brand"
SOURCE = ROOT / "index.html"
PAGES = ["shop.html", "product.html", "brand.html", "origin.html", "about.html", "rituals.html", "wishlist.html", "compact.html"]
NAMES = ["header", "footer", "bag", "search"]

LOGO = re.compile(r"(<!-- LOGO:(inline|img) ([\w.-]+)([^>]*?)-->)(.*?)(<!-- /LOGO -->)", re.S)


def block(name):
    return re.compile(
        rf"<!-- PARTIAL:{name} START -->.*?<!-- PARTIAL:{name} END -->", re.S)


def inline_svg(path):
    svg = path.read_text(encoding="utf-8")
    svg = re.sub(r"<\?xml.*?\?>|<!DOCTYPE.*?>|<!--.*?-->", "", svg, flags=re.S).strip()
    # decorative inside a labelled link: the <a> carries the accessible name
    svg = re.sub(r"\s(role|aria-label|aria-labelledby)=\"[^\"]*\"", "", svg)
    svg = svg.replace("<svg", '<svg class="brand-logo" aria-hidden="true" focusable="false"', 1)
    return svg


def fill_logos(html):
    missing = []

    def repl(m):
        opener, mode, fname, attrs, _body, closer = m.groups()
        path = BRAND / fname
        if not path.exists():
            missing.append(fname)
            return m.group(0)
        if mode == "inline":
            inner = inline_svg(path)
        else:
            alt = re.search(r'alt="([^"]*)"', attrs)
            width = re.search(r"width=(\d+)", attrs)
            cls = re.search(r'class="([^"]*)"', attrs)
            inner = (f'<img src="assets/brand/{fname}" alt="{alt.group(1) if alt else ""}"'
                     f'{f" width={chr(34)}{width.group(1)}{chr(34)}" if width else ""}'
                     f'{f" class={chr(34)}{cls.group(1)}{chr(34)}" if cls else ""}'
                     ' decoding="async">')
        return f"{opener}{inner}{closer}"

    return LOGO.sub(repl, html), missing


ENTRY = {"index.html": "js/pages/home.js", "shop.html": "js/pages/shop.js", "product.html": "js/pages/product.js",
         "brand.html": "js/pages/brand.js", "origin.html": "js/pages/origin.js", "about.html": "js/pages/about.js",
         "rituals.html": "js/pages/rituals.js", "wishlist.html": "js/pages/wishlist.js",
         "compact.html": "js/pages/compact.js"}
PRELOAD = re.compile(r"<!-- MODULEPRELOAD START.*?<!-- MODULEPRELOAD END -->", re.S)


def module_deps(entry):
    """Every module a page entry imports, directly or not (static imports only)."""
    seen, stack = [], [entry]
    while stack:
        f = stack.pop()
        if f in seen:
            continue
        seen.append(f)
        src = (ROOT / f).read_text(encoding="utf-8")
        for m in re.finditer(r'^import[^;]*?from\s+"(\.[^"]+)"', src, re.M):
            stack.append(posixpath.normpath(posixpath.join(posixpath.dirname(f), m.group(1))))
    return sorted(seen)


def with_preloads(page, html):
    links = "\n".join(f'<link rel="modulepreload" href="{d}">' for d in module_deps(ENTRY[page]))
    block = f"<!-- MODULEPRELOAD START (generated by tools/sync-partials.py) -->\n{links}\n<!-- MODULEPRELOAD END -->"
    if PRELOAD.search(html):
        return PRELOAD.sub(lambda _m: block, html)
    anchor = '<link rel="stylesheet" href="css/main.css">'
    return html.replace(anchor, anchor + "\n" + block, 1)


LCP = re.compile(r"<!-- PDP LCP START.*?<!-- PDP LCP END -->\n?", re.S)


def lcp_map():
    """{product id: [first gallery image, compact comparison image or ""]} from js/data/products.js
    (the product page's largest image, for the default size and for ?size=compact)."""
    js = (ROOT / "js" / "data" / "products.js").read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r'\{ id:"([^"]+)"(.*?)(?=\n  \{ id:"|\n\];|\n  // Update 03)', js, re.S):
        g = re.search(r'gallery:\[\s*\{ src:"([^"]+)"', m.group(2)) or re.search(r'hero:"([^"]+)"', m.group(2))
        c = re.search(r'key:"compact"[^}]*compare:"([^"]+)"', m.group(2))
        if g:
            out[m.group(1)] = [g.group(1), c.group(1) if c else ""]
    return out


def with_lcp(page, html):
    """product.html: preload this product's first image from the head (the page renders it from JS)."""
    if page != "product.html":
        return html
    pairs = ",".join(f'"{k}":["{v[0]}","{v[1]}"]' for k, v in lcp_map().items())
    script = ('<script>(function(m){var q=new URLSearchParams(location.search),e=m[q.get("id")];if(!e)return;'
              'var s=q.get("size")==="compact"&&e[1]||e[0];'
              'var l=document.createElement("link");l.rel="preload";l.as="image";l.href=s;l.fetchPriority="high";'
              'document.head.appendChild(l)})({' + pairs + '})</script>')
    block = ("<!-- PDP LCP START (generated by tools/sync-partials.py from js/data/products.js) -->\n"
             + script + "\n<!-- PDP LCP END -->")
    # Before any stylesheet: an inline script placed after one waits until that stylesheet has loaded.
    html = LCP.sub("", html)
    anchor = '<link rel="preconnect" href="https://fonts.googleapis.com">'
    return html.replace(anchor, block + "\n" + anchor, 1)


def main():
    check = "--check" in sys.argv
    src = SOURCE.read_text(encoding="utf-8")

    filled, missing = fill_logos(src)
    if missing:
        print("logo files not in assets/brand yet (interim kept):", ", ".join(sorted(set(missing))))
    filled = with_preloads("index.html", filled)
    if filled != src:
        if check:
            print("drift: index.html (logo slots or module preloads)")
        else:
            SOURCE.write_text(filled, encoding="utf-8", newline="\n")
            print("updated index.html (logo slots / module preloads)")
            src = filled

    partials = {}
    for n in NAMES:
        m = block(n).search(src)
        if not m:
            sys.exit(f"index.html is missing PARTIAL:{n}")
        partials[n] = m.group(0)

    drift = False
    for page in PAGES:
        path = ROOT / page
        html = path.read_text(encoding="utf-8")
        new = html
        for n, text in partials.items():
            if not block(n).search(new):
                sys.exit(f"{page} is missing PARTIAL:{n}")
            new = block(n).sub(lambda _m: text, new)
        new, _missing = fill_logos(new)   # page-specific slots too (e.g. the About lockup)
        new = with_preloads(page, new)
        new = with_lcp(page, new)
        if new != html:
            drift = True
            if check:
                print(f"drift: {page}")
            else:
                path.write_text(new, encoding="utf-8", newline="\n")
                print(f"synced: {page}")
    if check:
        print("partials identical" if not drift else "partials differ")
        sys.exit(1 if drift else 0)


if __name__ == "__main__":
    main()
